### ISSUE TITLE
test in the wild

### ISSUE THREAD

**Issue by ak9250** [bj80heyue/One_Shot_Face_Reenactment#1]
for testing on own images what is being used for cropping and extracting landmarks?

**Comment by bj80heyue** [comment]
Due to the protocol of company, the model to extract 106 + 40 facial landmarks cannot be released, however, if you want to get access to the following dataset, please fill in the license file in the repo (license/celebHQlms_license.pdf), then email the signed copy to siwei.1995@163.com to get access to the annotation dataset : )

**Comment by ak9250** [comment]
@bj80heyue ok, also what are you using to crop your ref images?
