### ISSUE TITLE
How to get 106 common facial key points & 20+20 gaze key points??

### ISSUE THREAD

**Issue by c1a1o1** [bj80heyue/One_Shot_Face_Reenactment#3]
How to get 106 common facial key points & 20+20 gaze key points??

**Comment by bj80heyue** [comment]
Due to the protocol of company, the model to extract 106 + 40 facial landmarks cannot be released, however, if you want to get access to the following dataset, please fill in the license file in the repo (license/celebHQlms_license.pdf), then email the signed copy to siwei.1995@163.com to get access to the annotation dataset : )
